version: "3.8"
services:
  notification-stage:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: ["node", "dist/main"]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      FLASK_ENV: production
    env_file:
      - .env

networks:
  default:
    name: network-numberapi-stage
    external: true