version: "3.8"
services:
  notification:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: ["node", "dist/main"]
    volumes:
      - .:/numberapi-vk-notification-production
      - /numberapi-vk-notification-production/node_modules
    env_file:
      - .env

networks:
  default:
    name: network-numberapi-production
    external: true