version: "3.8"

services:
  notification-stage:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/numberapi-vk-notification-stage
      - /numberapi-vk-notification-stage/node_modules

networks:
  default:
    name: network-numberapi-stage
    external: true