version: "3.8"

services:
  notification-production:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/numberapi-vk-notification-production
      - /numberapi-vk-notification-production/node_modules

networks:
  default:
    name: network-numberapi-production
    external: true